### ISSUE TITLE
Get all Tabs to markdown link

### ISSUE THREAD

**Issue by GChester** [eiichi-worker/browser-extension-markdown-link#2]
This is great work!!!

But why stop with a single tab?

It would be so much more awesome if it got all tabs and put in the clipboard.

**Comment by eiichi-worker** [comment]
Thank you!

There was no idea to copy all the tabs to the clipboard.
I will find time and implement it!

**Comment by eiichi-worker** [comment]
I made it possible to copy links on all tabs
I will close this issue
Thank you
